name: "Ecommerce CI"
on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: Setting up node js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Installing dependencies
        run: npm ci

      - name: "Docker build images"
        run: docker build -t ecommerce-app .

      - name: "Docker container run"
        run: docker run -d -p 3000:5555 --name ecommerce-container ecommerce-app
          