name: "Ecommerce CI"
on:
  pull_request:
    branches: [main]

jobs:
  build:
    uses: ubuntu-latest
    steps: 
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: Setting up node js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Installing dependencies
        run: npm ci    
          